idiff --git a/Makefile b/Makefile
index 465de76fe..d50279084 100644
--- a/Makefile
+++ b/Makefile
@@ -27,10 +27,6 @@ GO_VERSION ?= 1.25.12
 GO_DIRECTIVE_VERSION ?= 1.25.0
 GO_CONTAINER_IMAGE ?= docker.io/library/golang:$(GO_VERSION)

-# Ensure correct toolchain is used
-GOTOOLCHAIN = go$(GO_VERSION)
-export GOTOOLCHAIN
-
 # Use GOPROXY environment variable if set
 GOPROXY := $(shell go env GOPROXY)
 ifeq ($(GOPROXY),)
